import { IDataMatchHeader } from './interfaces';
import {
    dateConverter,
    clearConverter,
    genderConverter,
    replaceConverter
} from './converters';

export const dataMatchHeaders: IDataMatchHeader[] = [
    { id: 'DCA', name: 'vehicleClass', converters: [clearConverter] },
    { id: 'DCB', name: 'restrictionCodes', converters: [clearConverter] },
    { id: 'DCD', name: 'endorsementCodes', converters: [clearConverter] },
    { id: 'DBA', name: 'expirationDate', converters: [clearConverter, dateConverter] },
    { id: 'DAA', name: 'fullName', converters: [clearConverter, replaceConverter(/,/g, ', '), replaceConverter(/\s\s/g, ' ')] },
    { id: 'DAB', name: 'familyName', converters: [clearConverter] },
    { id: 'DCS', name: 'familyName', converters: [clearConverter] },
    { id: 'DCT', name: 'firstName', converters: [clearConverter] },
    { id: 'DAC', name: 'firstName', converters: [clearConverter] },
    { id: 'DAD', name: 'middleName', converters: [clearConverter] },
    { id: 'DBD', name: 'issueDate', converters: [clearConverter, dateConverter] },
    { id: 'DBB', name: 'dateOfBirth', converters: [dateConverter] },
    { id: 'DBC', name: 'sex', converters: [clearConverter, genderConverter] },
    { id: 'DAY', name: 'eyeColor', converters: [clearConverter] },
    { id: 'DAU', name: 'height', converters: [clearConverter] },
    { id: 'DAL', name: 'address', converters: [clearConverter] },
    { id: 'DAG', name: 'address', converters: [clearConverter] },
    { id: 'DAI', name: 'city', converters: [clearConverter] },
    { id: 'DAJ', name: 'state', converters: [clearConverter] },
    { id: 'DAK', name: 'zip', converters: [clearConverter] },
    { id: 'DBJ', name: 'idNumber', converters: [clearConverter] },
    { id: 'DAQ', name: 'idNumber', converters: [clearConverter] },
    { id: 'DCF', name: 'discriminator', converters: [clearConverter] },
    { id: 'DCG', name: 'country', converters: [clearConverter] },
    { id: 'DDE', name: 'familyNameTruncation', converters: [clearConverter] },
    { id: 'DDF', name: 'firstNameTruncation', converters: [clearConverter] },
    { id: 'DDG', name: 'middleNameTruncation', converters: [clearConverter] },
    { id: 'DAH', name: 'address2', converters: [clearConverter] },
    { id: 'DAZ', name: 'hairColor', converters: [clearConverter] },
    { id: 'DCI', name: 'placeOfBirth', converters: [clearConverter] },
    { id: 'DCJ', name: 'auditInformation', converters: [clearConverter] },
    { id: 'DCK', name: 'inventoryControlNumber', converters: [clearConverter] },
    { id: 'DBO', name: 'otherFamilyName', converters: [clearConverter] },
    { id: 'DBN', name: 'otherFamilyName', converters: [clearConverter] },
    { id: 'DBP', name: 'otherGivenName', converters: [clearConverter] },
    { id: 'DBG', name: 'otherGivenName', converters: [clearConverter] },
    { id: 'DBR', name: 'suffixName', converters: [clearConverter] },
    { id: 'DBS', name: 'suffixName', converters: [clearConverter] },
    { id: 'DCU', name: 'nameSuffix', converters: [clearConverter] },
    { id: 'DCE', name: 'weightRange', converters: [clearConverter] },
    { id: 'DCL', name: 'race', converters: [clearConverter] },
    { id: 'DCH', name: 'federalCommercialVehicleCodes', converters: [clearConverter] },
    { id: 'DCM', name: 'standardVehicleClassification', converters: [clearConverter] },
    { id: 'DAR', name: 'standardClassificationCode', converters: [clearConverter] },
    { id: 'DAT', name: 'standardEndorsementCode', converters: [clearConverter] },
    { id: 'DCN', name: 'standardEndorsementCode', converters: [clearConverter] },
    { id: 'DAS', name: 'standardRestrictionCode', converters: [clearConverter] },
    { id: 'DCO', name: 'standardRestrictionCode', converters: [clearConverter] },
    { id: 'DCP', name: 'vehicleClassificationDescription', converters: [clearConverter] },
    { id: 'DCQ', name: 'endorsementCodeDescription', converters: [clearConverter] },
    { id: 'DCR', name: 'restrictionCodeDescription', converters: [clearConverter] },
    { id: 'DDA', name: 'complianceType', converters: [clearConverter] },
    { id: 'DDB', name: 'cardRevisionDate', converters: [clearConverter, dateConverter] },
    { id: 'DDC', name: 'hazmatEndorsementExpirationDate', converters: [clearConverter, dateConverter] },
    { id: 'DDD', name: 'limitedDurationDocumentIndicator', converters: [clearConverter] },
    { id: 'DAW', name: 'weightInPounds', converters: [clearConverter] },
    { id: 'DAX', name: 'weightInKilograms', converters: [clearConverter] },
    { id: 'DDH', name: 'under18Until', converters: [clearConverter, dateConverter] },
    { id: 'DDI', name: 'under19Until', converters: [clearConverter, dateConverter] },
    { id: 'DDJ', name: 'under21Until', converters: [clearConverter, dateConverter] },
    { id: 'DDK', name: 'organDonorIndicator', converters: [clearConverter] },
    { id: 'DDL', name: 'veteranIndicator', converters: [clearConverter] },
    { id: 'DBH', name: 'organDonor', converters: [clearConverter] },
    { id: 'DAT', name: 'endorsementsCode', converters: [clearConverter] },

    //New York
    { state: 'NY', id: 'ZNA', name: 'fullName', converters: [clearConverter, replaceConverter(/@/g, ', '), replaceConverter(/\s\s/g, ' ')] },

    //New Jersey
    { state: 'NY', id: 'ZNA', name: 'zna', version: 4, converters: [clearConverter] },
    { state: 'NY', id: 'ZNB', name: 'znb', version: 4, converters: [clearConverter] },
    { state: 'NY', id: 'ZNC', name: 'znc', version: 4, converters: [clearConverter] },
    { state: 'NY', id: 'ZNF', name: 'hairColor', converters: [clearConverter] },

    // California
    { id: 'ZCA', name: 'eyeColor', converters: [clearConverter] },
    { id: 'ZCA', name: 'zca', version: 4, converters: [clearConverter] },
    { id: 'ZCB', name: 'hairColor', converters: [clearConverter] },
    { id: 'ZCB', name: 'restriction', version: 4, converters: [clearConverter] },
    { id: 'ZCC', name: 'eyeColor', converters: [clearConverter] },
    { id: 'ZCD', name: 'hairColor', converters: [clearConverter] },
    { id: 'ZCE', name: 'comingOfAge', converters: [clearConverter] },
    { id: 'ZCF', name: 'provisionalUntil', converters: [clearConverter] },

    // Florida
    { id: 'ZFA', name: 'replacedDate', converters: [clearConverter, dateConverter] },
    { id: 'ZFB', name: 'specialRestrictions', converters: [clearConverter] },
    { id: 'ZFC', name: 'safeDriverIndicator', converters: [clearConverter] },
    { id: 'ZFD', name: 'sexualPredator', converters: [clearConverter] },
    { id: 'ZFE', name: 'sexOffenderStatute', converters: [clearConverter] },
    { id: 'ZFF', name: 'insulinDependent', converters: [clearConverter] },
    { id: 'ZFG', name: 'developmentalDisability', converters: [clearConverter] },
    { id: 'ZFH', name: 'hearingImpaired', converters: [clearConverter] },
    { id: 'ZFI', name: 'fishAndWildlifeDesignations', converters: [clearConverter] },
    { id: 'ZFJ', name: 'customerNumber', converters: [clearConverter] },

    // Ontario
    { state: 'ON', id: 'ZOA', name: 'fullName', converters: [clearConverter, replaceConverter(/,/g, ', '), replaceConverter(/\s\s/g, ' ')] },
    { state: 'ON', id: 'ZOZ', name: 'idNumber', converters: [clearConverter] },
];