import { IDataMatch } from './interfaces';
import {
    dateConverter,
    clearConverter,
    genderConverter,
    splitConverter
} from './converters';

export const dataMatchHeaders: IDataMatch = {
    DCA: { name: 'vehicleClass', converters: [clearConverter] },
    DCB: { name: 'restrictionCodes', converters: [clearConverter] },
    DCD: { name: 'endorsementCodes', converters: [clearConverter] },
    DBA: { name: 'expirationDate', converters: [clearConverter, dateConverter] },
    DCS: { name: 'familyName', converters: [clearConverter] },
    DAC: { name: 'firstName', converters: [clearConverter] },
    DAD: { name: 'middleName', converters: [clearConverter] },
    DBD: { name: 'issueDate', converters: [clearConverter, dateConverter] },
    DBB: { name: 'dateOfBirth', converters: [dateConverter] },
    DBC: { name: 'sex', converters: [clearConverter, genderConverter] },
    DAY: { name: 'eyeColor', converters: [clearConverter] },
    DAU: { name: 'height', converters: [clearConverter] },
    DAG: { name: 'address', converters: [clearConverter] },
    DAI: { name: 'city', converters: [clearConverter] },
    DAJ: { name: 'state', converters: [clearConverter] },
    DAK: { name: 'zip', converters: [clearConverter] },
    DAQ: { name: 'idNumber', converters: [clearConverter] },
    DCF: { name: 'discriminator', converters: [clearConverter] },
    DCG: { name: 'country', converters: [clearConverter] },
    DDE: { name: 'familyNameTruncation', converters: [clearConverter] },
    DDF: { name: 'firstNameTruncation', converters: [clearConverter] },
    DDG: { name: 'middleNameTruncation', converters: [clearConverter] },
    DAH: { name: 'address2', converters: [clearConverter] },
    DAZ: { name: 'hairColor', converters: [clearConverter] },
    DCI: { name: 'placeOfBirth', converters: [clearConverter] },
    DCJ: { name: 'auditInformation', converters: [clearConverter] },
    DCK: { name: 'inventoryControlNumber', converters: [clearConverter] },
    DBN: { name: 'otherFamilyName', converters: [clearConverter] },
    DBG: { name: 'otherGivenName', converters: [clearConverter] },
    DBS: { name: 'suffixName', converters: [clearConverter] },
    DCU: { name: 'nameSuffix', converters: [clearConverter] },
    DCE: { name: 'weightRange', converters: [clearConverter] },
    DCL: { name: 'race', converters: [clearConverter] },
    DCM: { name: 'standardVehicleClassification', converters: [clearConverter] },
    DCN: { name: 'standardEndorsementCode', converters: [clearConverter] },
    DCO: { name: 'standardRestrictionCode', converters: [clearConverter] },
    DCP: { name: 'vehicleClassificationDescription', converters: [clearConverter] },
    DCQ: { name: 'endorsementCodeDescription', converters: [clearConverter] },
    DCR: { name: 'restrictionCodeDescription', converters: [clearConverter] },
    DDA: { name: 'complianceType', converters: [clearConverter] },
    DDB: { name: 'cardRevisionDate', converters: [clearConverter, dateConverter] },
    DDC: { name: 'hazmatEndorsementExpirationDate', converters: [clearConverter, dateConverter] },
    DDD: { name: 'limitedDurationDocumentIndicator', converters: [clearConverter] },
    DAW: { name: 'weightInPounds', converters: [clearConverter] },
    DAX: { name: 'weightInKilograms', converters: [clearConverter] },
    DDH: { name: 'under18Until', converters: [clearConverter, dateConverter] },
    DDI: { name: 'under19Until', converters: [clearConverter, dateConverter] },
    DDJ: { name: 'under21Until', converters: [clearConverter, dateConverter] },
    DDK: { name: 'organDonorIndicator', converters: [clearConverter] },
    DDL: { name: 'veteranIndicator', converters: [clearConverter] },
    ZNA: { name: 'fullName', converters: [clearConverter, splitConverter('@')] }
};